[package]
name = "rustracing"
version = "0.1.5"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "OpenTracing API for Rust"
homepage = "https://github.com/sile/rustracing"
repository = "https://github.com/sile/rustracing"
readme = "README.md"
keywords = ["opentracing"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/rustracing"}
codecov = {repository = "sile/rustracing"}

[features]
stacktrace = [ "backtrace" ]
default = [ "stacktrace" ]

[dependencies]
backtrace = { version = "0.3", optional = true}
rand = "0.4"
trackable = "0.2"
